accounts/urls.py
from django.urls import path
from .views import register, user_login, user_logout

app_name = "accounts"

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
   
 
]

flashcards/urls.py
from django.urls import path
from .views import *  

app_name = "flashcards"

urlpatterns = [

     path('dashboard/', FlashcardCreateView.as_view(template_name='flashcards/dashboard.html'), name='dashboard'),
     path('create/category/', CategoryCreateView.as_view(), name='category_create'),
     path('category/<str:category_id>/', CategoryDetailView.as_view(), name='category_detail'),
     path('update_category/<str:category_id>/', CategoryUpdateView.as_view(), name= 'category_update'),
     path('delete_category/<str:category_id>/', CategoryDeleteView.as_view(), name= 'category_delete'),
     path('create/flashcard/<str:category_id>/', FlashcardCreateView.as_view(template_name='flashcards/flashcard/create_form.html'), name='flashcard_create'),
     path('edit/<int:pk>/', FlashcardUpdateView.as_view(), name= 'flashcard_update'),
     path('delete/<int:pk>/', FlashcardDeleteView.as_view(), name= 'flashcard_delete'),
     path('random/<str:category_id>/', RandomFlashcardsView.as_view(), name='random_flashcards'),
     path('completion_quiz/<str:category_id>/', CompletionQuizView.as_view(), name='completion_quiz'),
     path('quiz/<str:category_id>/', QuizView.as_view(), name='quiz'),  
     path('add_to_favorites/<int:flashcard_id>/', add_to_favorites, name='add_to_favorites'),  
    
     
            ]

flashcards_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect



urlpatterns = [
    path('', lambda request: redirect('flashcards:dashboard'), name='index'), 
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('flashcards.urls')),
 

]

flashcards/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.urls import reverse
from datetime import date
import uuid


class Category(models.Model):
    id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    category_name = models.CharField(max_length=100)
    count = models.PositiveIntegerField(default=0) 
   
    class Meta:
        verbose_name_plural = "Categories"
        
        indexes = [
            models.Index(fields=['user', 'category_name']),
        ]

    def __str__(self):
        return self.category_name
    
    def get_absolute_url(self):
        return reverse('flashcards:category_detail', args=[str(self.id)])
   

class Flashcard(models.Model):
    question =  models.CharField(max_length=1000)
    answer = models.CharField(max_length=1000)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    date_added = models.DateField(auto_now_add= True)
    repeated_date = models.DateField(null=True, blank=True)
    repetitions_num = models.IntegerField(default=0)
    correct_answers = models.IntegerField(default=0)
    wrong_answers = models.IntegerField(default=0)
    flashcard_display_count = models.PositiveIntegerField(default=0)
    flashcard_know_count = models.PositiveIntegerField(default=0)
    flashcard_dont_know_count = models.PositiveIntegerField(default=0)
    is_favorite = models.BooleanField(default=False)
    answers_ratio = models.DecimalField(default=0, decimal_places=2, max_digits=3)

    class Meta:
        verbose_name_plural = "Flashcards"
        indexes = [
            models.Index(fields=['user', '-question']),
        ]

    def __str__(self):
        return self.question


    @property
    def calculate_ratio(self):
        total_answers = self.correct_answers + self.wrong_answers
        if total_answers == 0:
            return 0

        correct_ratio = self.correct_answers / total_answers

        if self.flashcard_dont_know_count == 0:
            know_ratio = 1
        else:
            know_ratio = self.flashcard_know_count / (self.flashcard_know_count + self.flashcard_dont_know_count)
       
        final_ratio = (correct_ratio * 0.6) + (know_ratio * 0.4)
        return final_ratio

    
    def update_instance(self, is_correct):
        if is_correct:
            self.correct_answers +=1
        else:
            self.wrong_answers +=1
        self.repetitions_num +=1
        self.repeated_date = date.today()
        self.answers_ratio = self.calculate_ratio
        self.save()
   

flashcards/forms.py
from django import forms
from .models import Category, Flashcard

class CategoryForm(forms.ModelForm):
    category_name = forms.CharField(label='Category', required=True)
    
    class Meta:
        model = Category
        fields = ['category_name']

class FlashcardForm(forms.ModelForm):
    form_type = forms.CharField(widget=forms.HiddenInput(), initial="separate_fields")

    class Meta:
        model = Flashcard
        fields = ['question', 'answer', 'category', 'form_type']
        labels = {
            'question': 'Question',
            'answer': 'Answer',
            'category': 'Category',
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(FlashcardForm, self).__init__(*args, **kwargs)
        self.fields['category'].required = True
        self.fields['question'].widget.attrs['maxlength'] = 1000
        self.fields['answer'].required = False
        if user:
            self.fields['category'].queryset = Category.objects.filter(user=user)

flashcards/views.py
import random

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views import View
from django.views.decorators.http import require_POST
from django.views.generic import (CreateView, DeleteView, ListView, 
                                  UpdateView)
from .forms import CategoryForm, FlashcardForm  
from .models import Category, Flashcard


class CategoryMixin(LoginRequiredMixin, UserPassesTestMixin):  
    model = Category
    context_object_name = 'categories'
    
    def get_object(self):
        category_id = self.kwargs['category_id']
        return get_object_or_404(Category, pk=category_id)

    def test_func(self):
        return self.get_object().user == self.request.user
   
    
    def get_success_url(self):
        return reverse('flashcards:category_detail', kwargs={'pk': self.object.pk})
    

class CategoryCreateView(LoginRequiredMixin, CreateView): 
    form_class = CategoryForm
    template_name = 'flashcards/category/create_update_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        messages.success(self.request, 'Category has been created successfully.')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request,"Something went wrong. Try again.")
        return self.form_invalid(form)

class CategoryDetailView(CategoryMixin, ListView): 
    template_name = 'flashcards/category/detail.html'
    context_object_name = 'flashcards'

    def get_queryset(self):
        return Flashcard.objects.filter(category=self.get_object())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.get_object()
        return context

class CategoryUpdateView(CategoryMixin, UpdateView): 
    template_name = 'flashcards/category/create_update_form.html'
    fields = ['category_name']

    def get_success_url(self):
        return reverse ('flashcards:dashboard')   
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        messages.success(self.request, 'The category has been updated successfully.')
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.warning(self.request,"Something went wrong. Try again.")
        return self.form_invalid(form)

class CategoryDeleteView(CategoryMixin, DeleteView):   
    template_name = 'flashcards/category/delete.html'  
    
    def get_success_url(self):
        messages.success(self.request, 'The category has been deleted.')
        return reverse('flashcards:dashboard')
    

class CategoryDeleteView(DeleteView):
    model = Category
    template_name = 'flashcards/category/delete.html'
    context_object_name = 'category'

    def get_object(self, queryset=None):
        category_id = self.kwargs.get('category_id')
        return get_object_or_404(Category, pk=category_id)

    def get_success_url(self):
        messages.success(self.request, 'The category has been deleted.')
        return reverse('flashcards:dashboard')

    def test_func(self):
        category = self.get_object()
        return category.user == self.request.user
        
class FlashcardMixin(LoginRequiredMixin, UserPassesTestMixin):  
    model = Flashcard
    def test_func(self):
        return self.get_object().user == self.request.user

    def get_success_url(self):
        return self.get_object().category.get_absolute_url()

    
class FlashcardCreateView(LoginRequiredMixin, CreateView): 
    form_class = FlashcardForm
    redirect_url = 'flashcards:dashboard'
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context["category_id"] = self.kwargs.get("category_id")
        context["form"].fields["category"].initial = context["category_id"]
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    
    def create_flashcard(self, form):
        form_type = self.request.POST['form_type']
       
        if form_type == 'separate_fields':
            flashcard = form.save(commit=False)
            flashcard.user = self.request.user
            flashcard.save()
                
        elif form_type == 'list_data':
            flashcards = self.request.POST.get('question').split('\n')
            for entry in flashcards:
                flashcard_data = entry.strip().split('-')
                if len(flashcard_data) == 2:
                    question, answer = map(str.strip, flashcard_data)
                    question = question[:100]
                    answer = answer[:100]
                    flashcard = Flashcard(question=question, answer=answer, user=self.request.user, category_id=self.kwargs.get("category_id")) 
                    flashcard.save()
            
    def form_valid(self, form):
        self.create_flashcard(form)
        messages.success(self.request, "Flashcard added successfully.")
        category_id = self.kwargs.get("category_id")
        if category_id:
            return redirect('flashcards:category_detail', category_id=category_id)
        else:
            return redirect('flashcards:dashboard')

    def form_invalid(self, form):
        for field, errors in form.errors.items():
            for error in errors:
                messages.error(self.request, f"Error in {field}: {error}")
        return super().form_invalid(form)

class FlashcardUpdateView(FlashcardMixin, UpdateView): 
    fields = ['question', 'answer']
    template_name = 'flashcards/flashcard/update_form.html'  

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        messages.success(self.request, 'Flashcard has been updated successfully.')
        return super().form_valid(form)


class FlashcardDeleteView(FlashcardMixin,DeleteView):
    template_name = 'flashcards/flashcard/delete.html'  

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['return_url'] = self.get_success_url()
        return context

    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

class QuizMixin(LoginRequiredMixin):  
    def get_category_object(self,request,category_id):
        return get_object_or_404(Category, id=category_id, user=request.user)
 
    def get_random_flashcard(self, category, n=1):
        if category.count < 1:
            return None
        
        flashcards = Flashcard.objects.filter(category=category)
        flashcards_with_weights = []

        for flashcard in flashcards:
            weight = 1 / max(0.01, float(flashcard.answers_ratio))  
            flashcards_with_weights.append((flashcard, weight))

        selected_flashcards = random.sample(flashcards_with_weights, k=min(n, len(flashcards_with_weights)))

        if n == 1:
            return selected_flashcards[0][0]
        else:
            return [flashcard for flashcard, _ in selected_flashcards]


    def get(self, request, category_id):
        category = self.get_category_object(request,category_id)
        
        if category.count < 4:
            messages.warning(request, "Not enough flashcards in category (less than 4).")
            return redirect('flashcards:dashboard')

        
        random_flashcard = self.get_random_flashcard(category)  
        if not random_flashcard:
            messages.warning(request, "No flashcards in category.")
            return redirect('flashcards:dashboard')
        
        return render(request, self.template_name, {'category': category, 'random_flashcard': random_flashcard})

class RandomFlashcardsView(QuizMixin, View):   
    template_name = 'flashcards/flashcard/detail.html'  
    
    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        return response

    def post(self,request,category_id):
        question_id = request.POST.get('question_id')
        action = request.POST.get('action')
        flashcard = Flashcard.objects.get(pk=question_id)
        
        if action == 'know':
            flashcard.flashcard_know_count += 1
        elif action == 'dont_know':
            flashcard.flashcard_dont_know_count += 1
        
        flashcard.flashcard_display_count += 1
        flashcard.save()
        return redirect(reverse('flashcards:random_flashcards', args=[category_id]))

class QuizView(QuizMixin, View): 
    template_name = 'flashcards/quiz/quiz.html'

    def get(self, request, category_id):
        category = self.get_category_object(request,category_id)
        if category.count < 4:
            messages.warning(request, "Not enough flashcards in category (less than 4).")
            return redirect('flashcards:dashboard')
           
        choices = self.get_random_flashcard(category, n=4)
        if not choices:
            messages.warning(request, "No flashcards in category.")
            return redirect('flashcards:dashboard')
        
        question = random.choice(choices)
        random.shuffle(choices)
        return render(request, self.template_name, {'category': category, 'question': question, 'choices': choices})
    
    def post(self, request,category_id):
        category = self.get_category_object(request,category_id) 
        session_data = request.session.setdefault('quiz_data', {
         'category_id': category_id,   
        'question_count': 0,
        'correct_count': 0,
        'incorrect_count': 0,
        })

        if session_data['category_id'] != category_id:
            session_data['category_id'] = category_id
            session_data['question_count'] = 0

flashcards/templates/flashcards/category/create_update_form.html
{% extends "flashcards/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="medium-container">
        <h5>Category</h5>
        <form method="post" class="form">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Submit" class="button">
        </form>
    </div>
{% endblock %}

flashcards/templates/flashcards/category/delete.html
{% extends 'flashcards/base.html' %}
{% block content %}
<div class="medium-container">
  <p>Are you sure you want to delete this category?</p>
  <div class="inline-elements">
    <a href="{% url 'flashcards:category_detail' category.pk %}" class="secondary-button">Cancel</a>
    <form action="{% url 'flashcards:category_delete' category.pk %}" method="post">
      {% csrf_token %}
      <button type="submit" class="alert-button">Delete</button>
    </form>
  </div>
</div>
{% endblock %}

flashcards/templates/flashcards/category/detail.html
{% extends 'flashcards/base.html' %}
{% load flashcard_tags %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        $(".favorite-button").click(function(event) {
            event.preventDefault();
            var button = $(this);
            var flashcardId = button.data("flashcard-id");
            var csrfToken = button.closest("form").find("input[name='csrfmiddlewaretoken']")
        .val(); 
            var baseUrl = window.location.origin + "/add_to_favorites/" + flashcardId + "/";
            $.ajax({
                url: baseUrl,
                method: "POST",
                dataType: "json",
                headers: {
                    "X-CSRFToken": csrfToken
                },
                success: function(data) {
                    if (data.is_favorite) {
                        button.removeClass("bi-star").addClass("bi-star-fill");
                    } else {
                        button.removeClass("bi-star-fill").addClass("bi-star");
                    }
                },
                error: function(xhr, status, error) {
                    console.log("Error toggling favorite status.");
                    console.log("Status:", status);
                    console.log("Error:", error);
                }
            });
        });
    });
</script>

<div class="medium-container" style="width:55%">
    <a href="{% url 'flashcards:dashboard' %}" class="close-button">&times;</a>
    <div class="dropdown">
        <button class="dropbtn">{{ category.category_name}} &#11167;</button>
        <div class="dropdown-content">
            <a href="{% url 'flashcards:category_update' category.pk %}">Edit category</a>
            <a href="{% url 'flashcards:category_delete' category.pk %}">Delete category</a>
            <a href="{% url 'flashcards:flashcard_create' category.pk %}">Add flashcards</a>
        </div>
    </div>
    <div class="inline-elements">
        <a href="{% url 'flashcards:quiz' category_id=category.id %}" class="button">Start quiz</a>
        <a href="{% url 'flashcards:random_flashcards' category_id=category.id %}" class="button">Learn</a>
        <a href="{% url 'flashcards:completion_quiz' category_id=category.id %}" class="button">Completion test</a>
    </div>
    <br>
    <div class="tabs">
        <input type="radio" id="tab-1-1" name="tab-group-1" checked>
        <label for="tab-1-1">All Flashcards</label>
        <div>
            {% flashcards_by_category request.user category.pk %}
        </div>
        <input type="radio" id="tab-1-2" name="tab-group-1">
        <label for="tab-1-2">Learned</label>
        <div>
            {% learned_flashcards request.user category.pk %}
        </div>
        <input type="radio" id="tab-1-3" name="tab-group-1">
        <label for="tab-1-3">Studying</label>
        <div>
            {% studying_flashcards request.user category.pk %}
        </div>
        <input type="radio" id="tab-1-4" name="tab-group-1">
        <label for="tab-1-4">Favorites</label>
        <div>
            {% favourites_by_category request.user category.pk %}
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}